<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="4" ignored="4" total="12" passed="2" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[LOG: INFO : Creating browser instances]]>
    </line>
    <line>
      <![CDATA[LOG: INFO : Browser instance is ready ]]>
    </line>
    <line>
      <![CDATA[LOG: INFO : Closing browser instances]]>
    </line>
    <line>
      <![CDATA[LOG: INFO : Browser instances closed]]>
    </line>
  </reporter-output>
  <suite started-at="2024-02-20T07:29:09 IST" name="Sample" finished-at="2024-02-20T07:29:53 IST" duration-ms="43244">
    <groups>
    </groups>
    <test started-at="2024-02-20T07:29:09 IST" name="Events.xml" finished-at="2024-02-20T07:29:53 IST" duration-ms="43244">
      <class name="org.aia.testcases.ces.SampleTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:08 IST" name="setup" finished-at="2024-02-20T07:29:09 IST" duration-ms="938" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="initialTestSetup()[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:09 IST" name="initialTestSetup" finished-at="2024-02-20T07:29:09 IST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialTestSetup -->
        <test-method is-config="true" signature="setupBrowser()[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:09 IST" name="setupBrowser" finished-at="2024-02-20T07:29:09 IST" duration-ms="13" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[LOG: INFO : Creating browser instances]]>
            </line>
            <line>
              <![CDATA[LOG: INFO : Browser instance is ready ]]>
            </line>
          </reporter-output>
        </test-method> <!-- setupBrowser -->
        <test-method signature="Test1()[pri:1, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:09 IST" name="Test1" description="Validate Online JOIN for Architecture Firm using credit card." finished-at="2024-02-20T07:29:10 IST" duration-ms="736" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:10 IST" name="tearDown" finished-at="2024-02-20T07:29:10 IST" duration-ms="10" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test1 status=SUCCESS method=SampleTest.Test1()[pri:1, instance:org.aia.testcases.ces.SampleTest@55740540] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method retried="true" signature="Test2()[pri:2, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:10 IST" name="Test2" description="Validate Online JOIN for Architecture Firm using Echeck." finished-at="2024-02-20T07:29:16 IST" duration-ms="6046" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at org.aia.testcases.ces.SampleTest.Test2(SampleTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:16 IST" name="tearDown" finished-at="2024-02-20T07:29:16 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test2 status=SKIP method=SampleTest.Test2()[pri:2, instance:org.aia.testcases.ces.SampleTest@55740540] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method retried="true" signature="Test2()[pri:2, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:16 IST" name="Test2" description="Validate Online JOIN for Architecture Firm using Echeck." finished-at="2024-02-20T07:29:22 IST" duration-ms="6012" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at org.aia.testcases.ces.SampleTest.Test2(SampleTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method signature="Test2()[pri:2, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:22 IST" name="Test2" description="Validate Online JOIN for Architecture Firm using Echeck." finished-at="2024-02-20T07:29:28 IST" duration-ms="6028" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at org.aia.testcases.ces.SampleTest.Test2(SampleTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:22 IST" name="tearDown" finished-at="2024-02-20T07:29:22 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test2 status=SKIP method=SampleTest.Test2()[pri:2, instance:org.aia.testcases.ces.SampleTest@55740540] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="Test3()[pri:3, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:28 IST" name="Test3" description="Validate Online JOIN for Architecture Firm using DD." finished-at="2024-02-20T07:29:34 IST" duration-ms="6024" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:28 IST" name="tearDown" finished-at="2024-02-20T07:29:28 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test2 status=FAILURE method=SampleTest.Test2()[pri:2, instance:org.aia.testcases.ces.SampleTest@55740540] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method retried="true" signature="Test4()[pri:4, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:34 IST" name="Test4" description="Validate Online JOIN for Architecture Firm using DD." finished-at="2024-02-20T07:29:40 IST" duration-ms="6031" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at org.aia.testcases.ces.SampleTest.Test4(SampleTest.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test4 -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:34 IST" name="tearDown" finished-at="2024-02-20T07:29:34 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test3 status=SUCCESS method=SampleTest.Test3()[pri:3, instance:org.aia.testcases.ces.SampleTest@55740540] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:40 IST" name="tearDown" finished-at="2024-02-20T07:29:40 IST" duration-ms="22" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test4 status=SKIP method=SampleTest.Test4()[pri:4, instance:org.aia.testcases.ces.SampleTest@55740540] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method retried="true" signature="Test4()[pri:4, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:40 IST" name="Test4" description="Validate Online JOIN for Architecture Firm using DD." finished-at="2024-02-20T07:29:46 IST" duration-ms="6029" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at org.aia.testcases.ces.SampleTest.Test4(SampleTest.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test4 -->
        <test-method signature="Test4()[pri:4, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:46 IST" name="Test4" description="Validate Online JOIN for Architecture Firm using DD." finished-at="2024-02-20T07:29:53 IST" duration-ms="6013" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at org.aia.testcases.ces.SampleTest.Test4(SampleTest.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test4 -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:46 IST" name="tearDown" finished-at="2024-02-20T07:29:46 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test4 status=SKIP method=SampleTest.Test4()[pri:4, instance:org.aia.testcases.ces.SampleTest@55740540] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:53 IST" name="tearDown" finished-at="2024-02-20T07:29:53 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Test4 status=FAILURE method=SampleTest.Test4()[pri:4, instance:org.aia.testcases.ces.SampleTest@55740540] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:53 IST" name="tearDown" finished-at="2024-02-20T07:29:53 IST" duration-ms="4" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[LOG: INFO : Closing browser instances]]>
            </line>
            <line>
              <![CDATA[LOG: INFO : Browser instances closed]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="finalTestTearDown(org.testng.ITestContext)[pri:0, instance:org.aia.testcases.ces.SampleTest@55740540]" started-at="2024-02-20T07:29:53 IST" name="finalTestTearDown" finished-at="2024-02-20T07:29:53 IST" duration-ms="9" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2a79d4b1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finalTestTearDown -->
      </class> <!-- org.aia.testcases.ces.SampleTest -->
    </test> <!-- Events.xml -->
  </suite> <!-- Sample -->
</testng-results>
